Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Estoque.Models
{
    public class Produto
    {

        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public int Quantidade { get; set; }
        public double Preco { get; set; }
        public int CategoriaId { get; set; }
        public Categoria Categoria { get; set; }

        public ICollection<Movimentacao> Movimentacoes { get; set; }

    }
}

Controllers/MovimentacoesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Estoque.Models;

namespace Estoque.Controllers
{
    public class MovimentacoesController : Controller
    {
        private readonly Contexto _contexto;

        public MovimentacoesController(Contexto contexto)
        {
            _contexto = contexto;
        }

        [HttpGet]
        public IActionResult NovaMovimentacao(int produtoId)
        {
            Movimentacao movimentacao = new Movimentacao
            { ProdutoId = produtoId };

            return View(movimentacao);
        }

        [HttpPost]
        public async Task<IActionResult> NovaMovimentacao(Movimentacao movimentacao)
        {
            movimentacao.DataMovimentacao = DateTime.Now.ToString();

            if (ModelState.IsValid)
            {
                await _contexto.Movimentacoes.AddAsync(movimentacao);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("DetalhesProduto", "Produtos", new { produtoId = movimentacao.ProdutoId });
            }

            return View(movimentacao);
        }
    }
}

Controllers/ProdutosController.cs
using Estoque.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Estoque.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly Contexto _contexto;

        public ProdutosController(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _contexto.Produtos.Include(p => p.Categoria).ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> NovoProduto()
        {
            ViewData["CategoriaId"] = new SelectList(await _contexto.Categorias.ToListAsync(), "CategoriaId", "Nome");
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DetalhesProduto(int produtoId)
        {
            Produto produto = await _contexto.Produtos.Include(p => p.Categoria).FirstOrDefaultAsync(p => p.ProdutoId == produtoId);
            return View(produto);
        }

        [HttpPost]
        public async Task<IActionResult> NovoProduto(Produto produto)
        {
            if (ModelState.IsValid)
            {
                await _contexto.Produtos.AddAsync(produto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoriaId"] = new SelectList(await _contexto.Categorias.ToListAsync(), "CategoriaId", "Nome", produto.CategoriaId);
            return View(produto);
        }

        [HttpGet]
        public async Task<IActionResult> AtualizarProduto(int produtoId)
        {
            Produto produto = await _contexto.Produtos.FindAsync(produtoId);

            ViewData["CategoriaId"] = new SelectList(await _contexto.Categorias.ToListAsync(), "CategoriaId", "Nome", produto.CategoriaId);
            return View(produto);
        }

        [HttpPost]
        public async Task<IActionResult> AtualizarProduto(Produto produto)
        {
            if (ModelState.IsValid)
            {
                _contexto.Produtos.Update(produto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(await _contexto.Categorias.ToListAsync(), "CategoriaId", "Nome", produto.CategoriaId);
            return View(produto);
        }

        [HttpPost]
        public async Task<IActionResult> ExcluirProduto(int produtoId)
        {
            Produto produto = await _contexto.Produtos.FindAsync(produtoId);
            _contexto.Produtos.Remove(produto);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Produtos/AtualizarProduto.cshtml
@model Estoque.Models.Produto;

@{
    ViewData["Title"] = "Atualizar Produto " + Model.Nome;
}

<div class="container p-5">
    <div class="row">
        <div class="col-6 border border-light rouded p-5 shadow">
            <h6>Atualizar Produto @Model.Nome</h6>
            <hr />

            <form asp-action="AtualizarProduto">
                <input hidden asp-for="ProdutoId" />
                
                <div class="form-group">
                    <label>Nome</label>
                    <input asp-for="Nome" type="text" class="form-control form-control-sm" />
                </div>

                <div class="form-group">
                    <label>Quantidade</label>
                    <input asp-for="Quantidade" type="number" class="form-control form-control-sm" />
                </div>

                <div class="form-group">
                    <label>Preco</label>
                    <input asp-for="Preco" step="0,01" type="text" class="form-control form-control-sm" />
                </div>

                <div class="form-group">
                    <label>Categoria</label>
                    <select asp-for="CategoriaId" asp-items="ViewBag.CategoriaId" class="form-control form-control-sm"></select>
                </div>

                <div class="container">
                    <div class="pl-1">
                        <button type="submit" class="btn btn-sm btn-outline-primary">
                            Salvar
                        </button>
                    </div>

                    <div class="pl-1">
                        <a class="btn btn-sm btn-light" asp-action="Index">Voltar</a>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>

Views/Produtos/DetalhesProduto.cshtml
@model Estoque.Models.Produto

@{ 
    ViewData["Title"] = "Detalhes e movimentacoes do produto " + Model.Nome;
}

<div class="container">
    <div class="row">
        <div class="col-10 border border-light rounded p-5">
            <h5 class="text-primary"><strong>Detalhes e movimentacoes do produto @Model.Nome</strong></h5>
            <hr/>
            <h6>Quantidade - @Model.Quantidade</h6>
            <h6>Preco - @Model.Preco</h6>
            <h6>Categoria - @Model.Categoria.Nome</h6>
            <hr/>

            <div class="container border border-light rounded shadow p-5">
                <div class="row">
                    <div class="col-8">
                        <h6>Movimentacoes</h6>
                    </div>

                    <div class="col-4">
                        <a asp-action="NovaMovimentacao" asp-controller="Movimentacoes" asp-route-produtoId="@Model.ProdutoId" class="btn btn-sm btn-outline-success">
                            Nova Movimentacao
                        </a>
                    </div>
                </div>
                <hr />
                
            </div>

        </div>
    </div>
</div>

Views/Produtos/Index.cshtml
@model IEnumerable<Estoque.Models.Produto>

@{
    ViewData["Title"] = "Produtos Registrados";
}

<div class="container p-5">
    <div class="border border-light rounded p-5">
        <a asp-controller="Produtos" asp-action="NovoProduto" class="btn btn-sm btn-outline-info">
            Novo Produto
        </a>

        <hr />

        <table class="table table-striped table-hover table-sm">
            <thead>
                <tr class="thead-light">
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Quantidade)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Preco)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Categoria.Nome)
                    </th>

                    <th>
                        Ações
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                 {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Quantidade)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Preco)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Categoria.Nome)
                    </td>

                    <td>
                        <div class="row">
                            <a asp-controller="Produtos" asp-action="AtualizarProduto" asp-route-produtoId="@item.ProdutoId" class="btn btn-sm btn-outline-primary">
                                <i class="fa fa-pencil-square-o"></i>
                            </a>

                            <a asp-controller="Produtos" asp-action="DetalhesProduto" asp-route-produtoId="@item.ProdutoId" class="btn btn-sm btn-outline-warning">
                                <i class="fa fa-tasks"></i>
                            </a>

                            <form asp-controller="Produtos" asp-action="ExcluirProduto" asp-route-produtoId="@item.ProdutoId">
                                <button type="submit" class="btn btn-sm btn-outline-danger">
                                    <i class="fa fa-times-circle"></i>
                                </button>
                            </form>

                        </div>
                    </td>

                </tr>
                 }
            </tbody>

        </table>
    </div>
</div>

Views/Produtos/NovoProduto.cshtml
@model Estoque.Models.Produto;

@{
    ViewData["Title"] = "Novo Produto";
}

<div class="container p-5">
    <div class="row">
        <div class="col-6 border border-light rouded p-5 shadow">
            <h6>Novo Produto</h6>
            <hr />

            <form asp-action="NovoProduto">
                <div class="form-group">
                    <label>Nome</label>
                    <input asp-for="Nome" type="text" class="form-control form-control-sm" />
                </div>

                <div class="form-group">
                    <label>Quantidade</label>
                    <input asp-for="Quantidade" type="number" class="form-control form-control-sm" />
                </div>

                <div class="form-group">
                    <label>Preco</label>
                    <input asp-for="Preco" step="0,01" type="text" class="form-control form-control-sm" />
                </div>

                <div class="form-group">
                    <label>Categoria</label>
                    <select asp-for="CategoriaId" asp-items="ViewBag.CategoriaId" class="form-control form-control-sm"></select>
                </div>

                <div class="container">
                    <div class="pl-1">
                        <button type="submit" class="btn btn-sm btn-outline-success">
                            Salvar
                        </button>
                    </div>

                    <div class="pl-1">
                        <a class="btn btn-sm btn-light" asp-action="Index">Voltar</a>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>